org: kennynguyen110702
app: first-terraform-with-serverless
service: terraform-serverless-integration
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev

functions:
  rdsConnector:
    handler: handler.handle
    environment:
      DATABASE_ENDPOINT: ${ssm:/database/testdb/endpoint~true}
      DATABASE_NAME: ${ssm:/database/testdb/name~true}
      DATABASE_USER: ${ssm:/database/testdb/user~true}
      DATABASE_PASSWORD: ${ssm:/database/testdb/password~true}
    events:
      - http:
          method: GET
          path: /
